### ISSUE TITLE
MVP - User Stories

### ISSUE THREAD

**Issue by PrimalOrB** [PrimalOrB/find_your_drink#14]
Define for MVP:
- [x] User Stories
- [x] Acceptance Criteria

Does not need to consider 'additional' features

**Comment by MarilynPapadopoulos** [comment]
This is partially completed in the Google Doc under API_Flow_1

**Comment by MarilynPapadopoulos** [comment]
AS A cocktail enthusiast
I WANT to be presented with new and fun drink ideas and recipes
SO THAT I CAN virtually cheers my friends 

GIVEN a drink idea generator
WHEN I am on the homepage
THEN I am presented with a random drink, with image and recipe
WHEN the random drink is displayed
THEN it is stored in a local storage list as recently viewed
WHEN viewing the page
THEN current date is displayed
WHEN the current date is displayed
THEN I am presented with a historical fact related to that date
WHEN I click a share button
THEN an email is generated that I can send to my contacts

**Comment by PrimalOrB** [comment]
This I think we will all need to talk about. I see the automated scheduled email functionality as going beyond the scope of a front end project, and we would spend a lot of time trying to sort something like this out.

@MissAimeeJay and I discussed a potential work around / method, which we can all review tonight

**Comment by MarilynPapadopoulos** [comment]
I think we can generate the email content and then the user can send the email.  I'm not sure if that is the solution....

**Comment by PrimalOrB** [comment]
Yeah, see #9 for my proposal as to how it might be able to work
